### ISSUE TITLE
enable regular merging (no squash, no rebase)

### ISSUE THREAD

**Issue by klahnakoski** [armenzg/smart-scheduling#17]
Squash-and-merge, and rebase both destroy diff information and prevents subsequent merging from another working branch.

Please enable regular merging so we can use it on our PRs.

**Comment by armenzg** [comment]
Hi Kyle,
Is it so you can preserve every commit on a PR?

**Comment by klahnakoski** [comment]
That is a side effect with some benefits.  What is most important is letting Git have the information to handle merges between multiple parallel branches.  That allows development of a feature along one branch with occasional merges into the master and vis-versa.

A merge commit includes extra information about how conflicts are resolved: It ensures the two children of a merge are the same code.  This information can be used so that **only future changes can cause merge conflicts in either branch**.  
* A rebase removes the distinction between a feature change and the merge change; any future work on the feature branch must re-resolve the same conflicts if it is to be merged. As programmer, you are forced to synchronize your feature work and the master work; if landing takes time, then feature work is halted until the rebase is done.
* A squash-and-merge does the job of separating the feature changes from the merge changes but leaves the original branch an orphan. This can be resolved, but it is error prone work: The squashed revision and the matching feature revision must be identified, then the rest of the feature must be rebased atop the squash. In other words, the programmer is forced to identify the synchronization point to resume work on a feature.

The default Git `merge` keeps both the feature branch and the merge change so there is no synchronization required; programming can proceed on the feature branch while waiting for the merge commit to land on master.

**Comment by klahnakoski** [comment]
http://paul.stadig.name/2010/12/thou-shalt-not-lie-git-rebase-ammend.html

**Comment by armenzg** [comment]
If you've noticed both Treeherder and mozci have this feature disabled and many have worked hard to keep it that way. Specially because it makes reading the commit history of `master` a breeze.

I'm willing to reach a compromise and enable it if you only use it when absolutely necessary (e.g. having more than 1 PR depending on each other) and try to reduce the number of commits on those PRs (or have them been few but with maningful messages).

It's *really* annoying when dozens of commits with unuseful messages for 1 PR landing on `master`. Reading the commit history becomes really awful.
